server :
  port: 8888
  servlet:
    context-path: /totvs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contas
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
        
        
